weights: weights/yolov5s.pt
cfg: ''
data: /mnt/c/users/bryce/ee595/yolov5_obb/data/final_box.yaml
hyp: runs/train/exp50/hyp.yaml
epochs: 1000
batch_size: 4
imgsz: 832
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 0
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp87
